# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
import datetime
from typing import Any, Optional
import uuid


@dataclasses.dataclass()
class Gpxfile:
    id: uuid.UUID
    gpxid: str
    filepath: str
    checksum: str


@dataclasses.dataclass()
class Record:
    id: uuid.UUID
    userid: str
    fileid: uuid.UUID
    trailname: str
    recordedat: Optional[datetime.datetime]
    duration: Optional[float]
    distance: Optional[float]
    ascent: Optional[float]
    descent: Optional[float]


@dataclasses.dataclass()
class Traildatum:
    id: uuid.UUID
    recordid: uuid.UUID
    traildata: Any


@dataclasses.dataclass()
class User:
    userid: str
